language: node_js
node_js: "stable"

before_install:
  - stty cols 80

dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
env:
  - SCREEN_WIDTH=3840 SCREEN_HEIGHT=2160

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &